global:
  scrape_interval: 15s
  external_labels:
    monitor: 'demo-monitor'

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'service'
    target_groups:
      - targets: [ 'localhost:9990' ]
